encoding: utf-8
# standard jekyll configuration

permalink: /:title/
highlighter: rouge
exclude: ['Rakefile',
          'config.rb',
          'README.md',
          'gems',
          'node_modules',
          '_src/scss/components',
          '*.sketch',
          'tips.md',
          'Gemfile',
          'Gemfile.*',
          'Gruntfile.*',
          'package.json',
          'yarn.*',
          'temp']
# markdown: rdiscount // kramdown : problem with tables // redcarpet: problem with more
markdown: kramdown

# gems: [jekyll-admin]

# configuration required for some pages

domain: css.yoksel.ru
url: http://css.yoksel.ru/
title: Про CSS
title_markup: '<span class="item item--about">Про</span> <span class="item item--css">CSS</span>'
description: Articles about CSS
author: yoksel
email: yoksel@yandex.ru

# feedburner:
#   id: feedburnerid

github:
    username: github/yoksel

# disqus:
#     id:

excerpt_separator: <!--more-->

env: prod

topmenu:
- name: 'Главная'
  url: '/'
- name: 'О сайте'
  url: '/about/'

links_title: Ссылки по теме
