encoding: utf-8
# standard jekyll configuration

permalink: /:title/
highlighter: rouge
exclude: ['Rakefile',
          'config.rb',
          'README.md',
          'gems',
          'node_modules',
          '_src/scss/components',
          '*.sketch',
          'tips.md',
          'Gemfile',
          'Gemfile.*',
          'Gruntfile.*',
          'package.json',
          'yarn.*',
          'temp']
# markdown: rdiscount // kramdown : problem with tables // redcarpet: problem with more
markdown: kramdown

# gems: [jekyll-admin]

# configuration required for some pages

domain: css.yoksel.ru
url: http://css.yoksel.ru/
title: Про CSS
title_markup: '<span class="item item--about">Про</span> <span class="item item--css">CSS</span>'
description: Articles about CSS
author: yoksel
email: yoksel@yandex.ru

# feedburner:
#   id: feedburnerid

github:
    username: github/yoksel

# disqus:
#     id:

excerpt_separator: <!--more-->

env: prod

topmenu:
- name: 'Главная'
  url: '/'
- name: 'О сайте'
  url: '/about/'

links_title: Ссылки по теме

links_docs:
- url: http://www.w3.org/
  name: W3C
- url: https://developer.mozilla.org/
  name: developer.mozilla.org
- url: http://learn.javascript.ru/
  name: learn.javascript.ru

links_blogs:
- url: http://lea.verou.me/
  name: Lea Verou
- url: http://nicolasgallagher.com/
  name: Nicolas Gallagher
- url: http://csswizardry.com/
  name: Csswizardry.com
- url: http://sarasoueidan.com/
  name: Sara Soueidan
- url: http://css-tricks.com
  name: Сss-tricks.com
- url: http://tympanus.net/codrops/
  name: Сodrops
- url: http://css-weekly.com/archives/
  name: CSS Weekly
- url: http://css-live.ru/
  name: CSS-Live
- url: http://frontender.info/
  name: Frontender Magazine

links_usefull:
- url: http://yoksel.github.io/flex-cheatsheet/
  name: Flexbox cheatsheet
- url: https://github.com/yoksel/pixel-glass-js
  name: Pixel Glass
- url: http://yoksel.github.io/html-tree/
  name: HTML Tree
- url: https://yoksel.github.io/handy-colors/
  name: Handy colors
- url: http://yoksel.github.io/unicode-table/
  name: Символы юникода
- url: http://yoksel.github.io/url-encoder/
  name: URL-encoder для SVG

links_projects:
- url: http://yoksel.github.io/flex-cheatsheet/
  name: Flexbox Cheatsheet
  desc: шпаргалка по флексбоксам, с живыми демками и описаниями из спеки
- url: https://github.com/yoksel/pixel-glass-js
  name: Pixel Glass
  desc: небольшой скрипт для проверки разметки на соответствие макету
- url: http://yoksel.github.io/html-tree/
  name: HTML Tree
  desc: генератор структуры документа с проверкой БЭМ-классов
- url: https://github.com/yoksel/common-words
  name: Common Words
  desc: слова, часто используемые в CSS-классах
- url: https://yoksel.github.io/handy-colors/
  name: Handy Colors
  desc: список именованных цветов с готовыми палитрами
- url: http://yoksel.github.io/unicode-table/
  name: Символы юникода
- url: http://yoksel.github.io/url-encoder/
  name: URL-encoder для SVG
- url: https://github.com/yoksel/shadowPainter
  name: Shadow Painter
  desc: рисовалка пиксельных анимаций на основе box-shadow

links_profiles:
- url: https://twitter.com/yoksel
  name: 'yoksel'
- url: https://twitter.com/yoksel_en
  name: 'yoksel_en'
- url: https://github.com/yoksel
  name: github.com/yoksel
- url: https://www.npmjs.org/~yoksel
  name: npmjs.org/~yoksel
- url: http://codepen.io/yoksel/
  name: codepen.io/yoksel
- url: http://yoksel.livejournal.com/
  name: yoksel.livejournal.com
- url: http://journals-covers.livejournal.com/
  name: journals-covers.livejournal.com
- url: http://colourlovers.com/lover/yoksel
  name: colourlovers.com/lover/yoksel
