- url: https://twitter.com/yoksel
  name: 'yoksel'

- url: https://twitter.com/yoksel_en
  name: 'yoksel_en'

- url: https://github.com/yoksel
  name: github.com/yoksel

- url: https://www.npmjs.org/~yoksel
  name: npmjs.org/~yoksel

- url: http://codepen.io/yoksel/
  name: codepen.io/yoksel

- url: http://yoksel.livejournal.com/
  name: yoksel.livejournal.com

- url: http://journals-covers.livejournal.com/
  name: journals-covers.livejournal.com

- url: http://colourlovers.com/lover/yoksel
  name: colourlovers.com/lover/yoksel
